### ISSUE TITLE
KeyError: 'Primary_Acc'

### ISSUE THREAD

**Issue by CLZHANG96** [pachterlab/gget#115]
### What happened?

Hi,when running 'gget elm -o results --uniprot Q02410', I got the error below. Can you please help me out?

Sun Dec 10 16:39:39 2023 INFO ELM_Classes_Download_Version: 1.4, ELM_Classes_Download_Date: 2023-12-10 09:30:34.601134
Sun Dec 10 16:39:39 2023 INFO <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">, <html><head>
Sun Dec 10 16:39:39 2023 INFO ORTHO Compiling ortholog information...
Traceback (most recent call last):
  File "/home/data/t010219/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Primary_Acc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/data/t010219/miniconda3/envs/wgs/bin/gget", line 8, in <module>
    sys.exit(main())
  File "/home/data/t010219/miniconda3/envs/wgs/lib/python3.8/site-packages/gget/main.py", line 1954, in main
    ortho, regex = elm(
  File "/home/data/t010219/miniconda3/envs/wgs/lib/python3.8/site-packages/gget/gget_elm.py", line 282, in elm
    ortho_df = get_elm_instances(sequence)
  File "/home/data/t010219/miniconda3/envs/wgs/lib/python3.8/site-packages/gget/gget_elm.py", line 48, in get_elm_instances
    df_full_instances["Primary_Acc"] == UniProtID
  File "/home/data/t010219/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/data/t010219/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'Primary_Acc'

### gget version

0.28.2

### Operating System (OS)

Linux

### User interface

Command-line

### Are you using a computer with an Apple M1 chip?

Not M1

### What is the exact command that was run?

```shell
gget elm -o results --uniprot Q02410
```

### Which output/error did you get?

```shell
Sun Dec 10 16:39:39 2023 INFO ELM_Classes_Download_Version: 1.4, ELM_Classes_Download_Date: 2023-12-10 09:30:34.601134
Sun Dec 10 16:39:39 2023 INFO <!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">, <html><head>
Sun Dec 10 16:39:39 2023 INFO ORTHO Compiling ortholog information...
Traceback (most recent call last):
  File "/home/data/t010219/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Primary_Acc'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/data/t010219/miniconda3/envs/wgs/bin/gget", line 8, in <module>
    sys.exit(main())
  File "/home/data/t010219/miniconda3/envs/wgs/lib/python3.8/site-packages/gget/main.py", line 1954, in main
    ortho, regex = elm(
  File "/home/data/t010219/miniconda3/envs/wgs/lib/python3.8/site-packages/gget/gget_elm.py", line 282, in elm
    ortho_df = get_elm_instances(sequence)
  File "/home/data/t010219/miniconda3/envs/wgs/lib/python3.8/site-packages/gget/gget_elm.py", line 48, in get_elm_instances
    df_full_instances["Primary_Acc"] == UniProtID
  File "/home/data/t010219/.local/lib/python3.8/site-packages/pandas/core/frame.py", line 3505, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/home/data/t010219/.local/lib/python3.8/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
KeyError: 'Primary_Acc'
```

**Comment by lauraluebbert** [comment]
Hi, thank you for reaching out. I am having trouble reproducing this error (see [this Colab notebook](https://colab.research.google.com/drive/1qsqC5vRYMMHD-uyYmr-Vp2mq3u-q8TAP?usp=sharing)). Could you please update pandas (`pip install -U pandas`) and try again?

**Comment by CLZHANG96** [comment]
Hi,thaks for your timely assistant.After running "pip install -U pandas" ,it still didn't work.But after rerunning "gget setup elm",everything goes well.Wishing you a pleasant and joyful work and life!

**Comment by lauraluebbert** [comment]
Ok, maybe something went wrong the first time the database was downloaded. I’m glad it works now. Please let me know if you encounter any other issues in the future. Happy holidays! :)
