### ISSUE TITLE
Very cool tool -- unfortunately it appears that the `gpt` module is not working

### ISSUE THREAD

**Issue by adeslatt** [pachterlab/gget#166]
### What happened?

I tried both on the command line as well as within a python notebook and I get this error:

In python,
```python
import gget

gget.setup("gpt")
```
returns the following error:
```python
SyntaxWarning: invalid escape sequence '\[/](http://localhost:8888/)'
  command = """
[/Users/annedeslattesmays/miniconda3/envs/scverse/lib/python3.12/site-packages/gget/gget_setup.py:155](http://localhost:8888/Users/annedeslattesmays/miniconda3/envs/scverse/lib/python3.12/site-packages/gget/gget_setup.py#line=154): SyntaxWarning: invalid escape sequence '\[/](http://localhost:8888/)'
  "[/](http://localhost:8888/)", "\[/](http://localhost:8888/)"
[/Users/annedeslattesmays/miniconda3/envs/scverse/lib/python3.12/site-packages/gget/gget_setup.py:162](http://localhost:8888/Users/annedeslattesmays/miniconda3/envs/scverse/lib/python3.12/site-packages/gget/gget_setup.py#line=161): SyntaxWarning: invalid escape sequence '\[/](http://localhost:8888/)'
  command = """
[/Users/annedeslattesmays/miniconda3/envs/scverse/lib/python3.12/site-packages/gget/gget_setup.py:171](http://localhost:8888/Users/annedeslattesmays/miniconda3/envs/scverse/lib/python3.12/site-packages/gget/gget_setup.py#line=170): SyntaxWarning: invalid escape sequence '\[/](http://localhost:8888/)'
  "[/](http://localhost:8888/)", "\[/](http://localhost:8888/)"
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[4], line 1
----> 1 gget.setup("gpt")

File [site-packages/gget/gget_setup.py:45]
     43 supported_modules = ["alphafold"]
     44 if module not in supported_modules:
---> 45     raise ValueError(
     46         f"'module' argument specified as {module}. Expected one of: {', '.join(supported_modules)}"
     47     )
     49 if module == "alphafold":
     50     ## Make sure package paths are appended so openmm can be imported
     51     site_packages_path = os.__file__.split("os.py")[0] + "site-packages"

ValueError: 'module' argument specified as gpt. Expected one of: alphafold
```

also from the command line a similar error
```bash
gget setup gpt  
```

returns
```bash
gget setup: error: argument module: invalid choice: 'gpt' (choose from 'alphafold')
```

### gget version

0.29.0

### Operating System (OS)

macOS

### User interface

Command-line, Python

### Are you using a computer with an Apple M1 chip?

Not M1

**Comment by lauraluebbert** [comment]
HI Anne, thank you for reaching out. This looks to me like an older version of gget might be installed. Could you please try again after running `pip install --upgrade --force-reinstall gget`? Which version is shown when you run `gget -v`?

**Comment by adeslatt** [comment]
Hi Laura,
I was in an environment where I had previously installed cellxgene-census and when I did the `pip install --force-reinstall gget` I got a conflict with NumPy saying that cellxgene-census as follows:

**Comment by lauraluebbert** [comment]
Hi, sorry are you still getting an error?

**Comment by adeslatt** [comment]
Hi @lauraluebbert , 
gget seems to be returning results for all commands, but I do see this:
```bash

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/bin/gget", line 5, in <module>
    from gget.main import main
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gget/__init__.py", line 1, in <module>
    from .gget_ref import ref
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gget/gget_ref.py", line 6, in <module>
    from .utils import (
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gget/utils.py", line 9, in <module>
    import pandas as pd
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pandas/compat/__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.1.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/bin/gget", line 5, in <module>
    from gget.main import main
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gget/__init__.py", line 1, in <module>
    from .gget_ref import ref
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gget/gget_ref.py", line 6, in <module>
    from .utils import (
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/gget/utils.py", line 9, in <module>
    import pandas as pd
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/Users/annedeslattesmays/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib
AttributeError: _ARRAY_API not found
```

with every command I run -- but I do see the results.

**Comment by adeslatt** [comment]
I just did the following:
```bash
pip install --force-reinstall pyarrow
```
and now I get no message and the warning or messages of doom seem to have disappeared!

**Comment by lauraluebbert** [comment]
Oh ok great, I'm glad everything works now and thank you for sharing! :) Feel free to reopen this issue if there are any new problems.
