### ISSUE TITLE
error in 'gget setup alphafold'

### ISSUE THREAD

**Issue by mikenada** [pachterlab/gget#167]
### What happened?

receive an error while setting up alphafold

### gget version

0.3.7

### Operating System (OS)

Linux

### User interface

Command-line

### Are you using a computer with an Apple M1 chip?

Not applicable

### What is the exact command that was run?

```shell
pip install --upgrade gget
** finish without error

gget setup alphafold
** see error below
```

### Which output/error did you get?

```shell
** see error below 
(base) dostvip2@DESKTOP-L5H6T8M:/mnt/f$ gget setup alphafold
Traceback (most recent call last):
  File "/home/dostvip2/miniconda3_v2/bin/gget", line 5, in <module>
    from gget.main import main
  File "/home/dostvip2/miniconda3_v2/lib/python3.12/site-packages/gget/__init__.py", line 1, in <module>
    from .gget_ref import ref
  File "/home/dostvip2/miniconda3_v2/lib/python3.12/site-packages/gget/gget_ref.py", line 6, in <module>
    from .utils import (
  File "/home/dostvip2/miniconda3_v2/lib/python3.12/site-packages/gget/utils.py", line 11, in <module>
    from IPython.display import display, HTML
  File "/home/dostvip2/miniconda3_v2/lib/python3.12/site-packages/IPython/__init__.py", line 55, in <module>
    from .terminal.embed import embed
  File "/home/dostvip2/miniconda3_v2/lib/python3.12/site-packages/IPython/terminal/embed.py", line 15, in <module>
    from IPython.core.interactiveshell import DummyMod, InteractiveShell
  File "/home/dostvip2/miniconda3_v2/lib/python3.12/site-packages/IPython/core/interactiveshell.py", line 110, in <module>
    from IPython.core.history import HistoryManager
  File "/home/dostvip2/miniconda3_v2/lib/python3.12/site-packages/IPython/core/history.py", line 10, in <module>
    import sqlite3
  File "/home/dostvip2/miniconda3_v2/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/dostvip2/miniconda3_v2/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ImportError: /home/dostvip2/miniconda3_v2/lib/python3.12/lib-dynload/_sqlite3.cpython-312-x86_64-linux-gnu.so: undefined symbol: sqlite3_deserialize
```

**Comment by mikenada** [comment]
Hello I did the ff

1. Downgrade python since in requires v3.10
mamba install -c conda-forge python=3.10

2 Install the ff: 
mamba install -c conda-forge requests==2.32.3
mamba install -qy -c conda-forge openmm=7.7.0
mamba install -c conda-forge sqlite==3.47.0

still, i received a new error as below: 

(gget_alphafold2) dostvip2@DESKTOP-L5H6T8M:~$ gget setup alphafold
-bash: /home/dostvip2/miniconda3/envs/gget_alphafold2/bin/gget: /home/dostvip2/miniconda3/envs/gget_alphafold2/bin/python3.13: bad interpreter: No such file or directory

**Comment by mikenada** [comment]
Oh Its seems working now (hopefully) : 

I created a new environment with python v3.10 and install everything on that environment.  I also encountered several errors due to incompatibility in the installed versions. Hence, I installed specific version as listed below. I think it would be beneficial if the required version/s were also listed in the github page. 

$ mamba create -n gget_alphafold2 python=3.10
$ conda activate gget_alphafold2
$ mamba install -c conda-forge requests==2.32.3
$ pip install --upgrade gget
$ mamba install -c conda-forge openmm=7.7.0
$ mamba install -c conda-forge sqlite==3.47.0
$ gget setup alphafold
$ pip install jax==0.4.34
$ pip install jax==1.26.4
$ gget alphafold <protein sequences here>

Will update this once the command finishes. 

<img width="956" alt="Screenshot 2024-11-11 141936" src="https://github.com/user-attachments/assets/f10785f6-6e4c-46da-9fb1-1ae0416be329">

**Comment by lauraluebbert** [comment]
Hi Mike, I'm glad the installation worked out and thank you for sharing the steps! The error above suggests a problem during the data retrieval over HTTPS. This happens rarely, especially when the internet connection in not stable. Unfortunately, the only solution is to try again. If there is anything you can do to secure the internet connection while the command is running that would be great! A better internet connection will also decrease the runtime.

**Comment by mikenada** [comment]
Hello @lauraluebbert Thanks for confirming that the installation works. Will try to re-run the analysis with a better internet connection.
