### ISSUE TITLE
Local variable 'db_connection' referenced before assignment

### ISSUE THREAD

**Issue by alexpreynolds** [pachterlab/gget#31]
Installed on host via `pip install --upgrade gget`:

```
$ system_profiler SPSoftwareDataType SPHardwareDataType
Software:

    System Software Overview:

      System Version: macOS 12.5 (21G72)
      Kernel Version: Darwin 21.6.0
      Boot Volume: Macintosh HD
      Boot Mode: Normal
      Computer Name: Earl Grey
      User Name: Alex Reynolds (areynolds)
      Secure Virtual Memory: Enabled
      System Integrity Protection: Enabled
      Time since boot: 1 day 8:44

Hardware:

    Hardware Overview:

      Model Name: MacBook Pro
      Model Identifier: MacBookPro16,4
      Processor Name: 8-Core Intel Core i9
      Processor Speed: 2.4 GHz
      Number of Processors: 1
      Total Number of Cores: 8
      L2 Cache (per Core): 256 KB
      L3 Cache: 16 MB
      Hyper-Threading Technology: Enabled
      Memory: 32 GB
      System Firmware Version: 1731.140.2.0.0 (iBridge: 19.16.16064.0.0,0)
      OS Loader Version: 540.120.3~19
      Serial Number (system): C02CT0C0PT01
      Hardware UUID: C6082A3D-359C-5F2C-AC84-5068C7891897
      Provisioning UDID: C6082A3D-359C-5F2C-AC84-5068C7891897
      Activation Lock Status: Disabled
```

Problematic command:

```
$ python --version
Python 3.8.13
$ gget search -s homo_sapiens 'usf1'
Tue Aug  9 20:03:08 2022 INFO Fetching results from database: homo_sapiens_core_107_38
Tue Aug  9 20:03:11 2022 ERROR The Ensembl server returned the following error: Character set 'utf8' unsupported
Traceback (most recent call last):
  File "/Users/areynolds/miniconda3/bin/gget", line 8, in <module>
    sys.exit(main())
  File "/Users/areynolds/miniconda3/lib/python3.8/site-packages/gget/main.py", line 1223, in main
    gget_results = search(
  File "/Users/areynolds/miniconda3/lib/python3.8/site-packages/gget/gget_search.py", line 172, in search
    df_temp = pd.read_sql(query, con=db_connection)
UnboundLocalError: local variable 'db_connection' referenced before assignment
```

Using version 0.3.7:

```
$ gget --version
gget version: 0.3.7
```

**Comment by lauraluebbert** [comment]
What is the version of your mysql-connector-python package? It seems like they changed the way utf8 is handled in the latest version ([reference](https://stackoverflow.com/questions/73244027/character-set-utf8-unsupported-in-python-mysql-connector)). 

Could you please downgrade mysql-connector-python (`pip install mysql-connector-python==8.0.29`) and try again?

**Comment by alexpreynolds** [comment]
Yeah, this might be fixed w/a patch to `requirements.txt`:

```
(base) areynolds@Earl-Grey ~ % pip install mysql-connector-python==8.0.29
Collecting mysql-connector-python==8.0.29
  Downloading mysql_connector_python-8.0.29-py2.py3-none-any.whl (342 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.0/342.0 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: protobuf>=3.0.0 in ./miniconda3/lib/python3.8/site-packages (from mysql-connector-python==8.0.29) (3.20.1)
Installing collected packages: mysql-connector-python
  Attempting uninstall: mysql-connector-python
    Found existing installation: mysql-connector-python 8.0.30
    Uninstalling mysql-connector-python-8.0.30:
      Successfully uninstalled mysql-connector-python-8.0.30
Successfully installed mysql-connector-python-8.0.29
(base) areynolds@Earl-Grey ~ % gget search -s homo_sapiens 'ace2'        
Tue Aug  9 20:20:41 2022 INFO Fetching results from database: homo_sapiens_core_107_38
Tue Aug  9 20:20:44 2022 INFO Total matches found: 3.
Tue Aug  9 20:20:44 2022 INFO Query time: 7.47 seconds.
[
    {
        "ensembl_id": "ENSG00000130234",
        "gene_name": "ACE2",
        "ensembl_description": "angiotensin converting enzyme 2 [Source:HGNC Symbol;Acc:HGNC:13557]",
        "ext_ref_description": "angiotensin converting enzyme 2",
        "biotype": "protein_coding",
        "url": "https://uswest.ensembl.org/homo_sapiens/Gene/Summary?g=ENSG00000130234"
    },
    {
        "ensembl_id": "ENSG00000182240",
        "gene_name": "BACE2",
        "ensembl_description": "beta-secretase 2 [Source:HGNC Symbol;Acc:HGNC:934]",
        "ext_ref_description": "beta-secretase 2",
        "biotype": "protein_coding",
        "url": "https://uswest.ensembl.org/homo_sapiens/Gene/Summary?g=ENSG00000182240"
    },
    {
        "ensembl_id": "ENSG00000224388",
        "gene_name": "BACE2-IT1",
        "ensembl_description": "BACE2 intronic transcript 1 [Source:HGNC Symbol;Acc:HGNC:16024]",
        "ext_ref_description": "BACE2 intronic transcript 1",
        "biotype": "lncRNA",
        "url": "https://uswest.ensembl.org/homo_sapiens/Gene/Summary?g=ENSG00000224388"
    }
]
```

**Comment by lauraluebbert** [comment]
Glad this worked! I already adjusted the requirements.txt; thank you for bringing this issue to my attention.

**Comment by alexpreynolds** [comment]
...which it appears has been done, so I'll close this up. Thanks!
