### ISSUE TITLE
AttributeError: module 'psutil' has no attribute 'Process'

### ISSUE THREAD

**Issue by najibveto** [pachterlab/gget#51]
hello,
I installed gget using the command:
pip install --upgrade gget
then when i tried to install alphafold using the command:
gget setup alphafold
I got the following error:
```
gget setup alphafold
Traceback (most recent call last):
  File "/home/najib/miniconda3/bin/gget", line 5, in <module>
    from gget.main import main
  File "/home/najib/miniconda3/lib/python3.9/site-packages/gget/__init__.py", line 10, in <module>
    from .gget_alphafold import alphafold
  File "/home/najib/miniconda3/lib/python3.9/site-packages/gget/gget_alphafold.py", line 31, in <module>
    from ipywidgets import GridspecLayout
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipywidgets/__init__.py", line 25, in <module>
    from .widgets import *
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipywidgets/widgets/__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipywidgets/widgets/widget.py", line 13, in <module>
    from ipykernel.comm import Comm
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipykernel/comm/__init__.py", line 3, in <module>
    from .comm import Comm
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipykernel/comm/comm.py", line 14, in <module>
    from ipykernel.kernelbase import Kernel
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 70, in <module>
    class Kernel(SingletonConfigurable):
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 79, in Kernel
    processes: t.Dict[str, psutil.Process] = {}
AttributeError: module 'psutil' has no attribute 'Process'
```
i uninstalled the psutil and installed again, i got the same error.
what is the possible solution?
thank you.

**Comment by lauraluebbert** [comment]
Hi, thanks for reaching out. I have not encountered this error before. My first recommendation would indeed be to reinstall psutil using something like `pip3 install --ignore-installed psutil`. Could you please tell me which version of gget and psutil you currently have installed?

**Comment by najibveto** [comment]
thank you for your reply.
i checked the version for gget and it is 0.27.2 and for psutill and it is 5.9.4.
i tried to reinstall psutil using 
`pip3 install --ignore-installed psutil`
and then run:
`gget setup alphafold`
i got the following error:
```
Traceback (most recent call last):
  File "/home/najib/miniconda3/bin/gget", line 5, in <module>
    from gget.main import main
  File "/home/najib/miniconda3/lib/python3.9/site-packages/gget/__init__.py", line 10, in <module>
    from .gget_alphafold import alphafold
  File "/home/najib/miniconda3/lib/python3.9/site-packages/gget/gget_alphafold.py", line 31, in <module>
    from ipywidgets import GridspecLayout
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipywidgets/__init__.py", line 25, in <module>
    from .widgets import *
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipywidgets/widgets/__init__.py", line 4, in <module>
    from .widget import Widget, CallbackDispatcher, register, widget_serialization
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipywidgets/widgets/widget.py", line 13, in <module>
    from ipykernel.comm import Comm
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipykernel/comm/__init__.py", line 3, in <module>
    from .comm import Comm
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipykernel/comm/comm.py", line 14, in <module>
    from ipykernel.kernelbase import Kernel
  File "/home/najib/miniconda3/lib/python3.9/site-packages/ipykernel/kernelbase.py", line 35, in <module>
    import psutil
  File "/home/najib/miniconda3/lib/python3.9/site-packages/psutil/__init__.py", line 241, in <module>
    raise ImportError(msg)
ImportError: version conflict: '/home/najib/miniconda3/lib/python3.9/site-packages/psutil/_psutil_linux.cpython-39-x86_64-linux-gnu.so' C extension module was built for another version of psutil (5.9.1 instead of 5.9.4); you may try to 'pip uninstall psutil', manually remove /home/najib/miniconda3/lib/python3.9/site-packages/psutil/_psutil_linux.cpython-39-x86_64-linux-gnu.so or clean the virtual env somehow, then reinstall
```

**Comment by lauraluebbert** [comment]
It looks like the psutil issue was fixed. It seems like there are some issues with other packages in your environment. I would recommend trying the following: 
First, reinstall/update numpy since the issue might be coming from numpy (`pip install -U numpy`).

If that doesn’t fix the issue, I would recommend restarting in a fresh Python environment ([conda environments manual](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)).

Alternatively, check out [this solution](https://stackoverflow.com/questions/54552367/pip-cannot-find-metadata-file-environmenterror). It might help fix the issue in the current environment.

**Comment by najibveto** [comment]
> It looks like the psutil issue was fixed. It seems like there are some issues with other packages in your environment. I would recommend trying the following: First, reinstall/update numpy since the issue might be coming from numpy (`pip install -U numpy`).
> 
> If that doesn’t fix the issue, I would recommend restarting in a fresh Python environment ([conda environments manual](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)).
> 
> Alternatively, check out [this solution](https://stackoverflow.com/questions/54552367/pip-cannot-find-metadata-file-environmenterror). It might help fix the issue in the current environment.

hello,
thank you for your suggestion.
i did as your suggestion and reinstall numpy and it is wokring fine.
thanks a lot.

**Comment by lauraluebbert** [comment]
Great! :)
