### ISSUE TITLE
gget alphafold: RuntimeError: jaxlib version 0.4.1 is newer than and incompatible with jax version 0.3.25. Please update your jax and/or jaxlib packages

### ISSUE THREAD

**Issue by tsucheta** [pachterlab/gget#55]
I have installed gget in my ubuntu 20.04. However, when I do a gget setup alphafold it sets it up fine as below:

Thu Jan 12 06:06:31 2023 INFO openmm v7.5.1 already installed.
Thu Jan 12 06:06:31 2023 INFO Installing AlphaFold from source (requires pip and git).
Thu Jan 12 06:06:37 2023 INFO AlphaFold installed succesfully.
Thu Jan 12 06:06:37 2023 INFO Installing pdbfixer from source (requires pip and git).
Thu Jan 12 06:06:41 2023 INFO pdbfixer installed succesfully.
Thu Jan 12 06:06:41 2023 INFO AlphaFold model parameters already downloaded.

However my run on 
gget alphafold MAAHKGAEHHHKAAEHHEQAAKHHHAAAEHHEKGEHEQAAHHADTAYAHHKHAEEHAAQAAKHDAEHHAPKPH

returns the following error. I have also tried doing  pip install -U gget followed by  pip install -U gget I still get the same error:

Traceback (most recent call last):
  File "/home/sutripa/anaconda3/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/main.py", line 70, in main
    return command.main(cmd_args)
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 98, in main
    return self._main(args)
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", line 214, in _main
    self.handle_pip_version_check(options)
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 143, in handle_pip_version_check
    session = self._build_session(
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", line 88, in _build_session
    session = PipSession(
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_internal/network/session.py", line 289, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_internal/network/session.py", line 132, in user_agent
    linux_distribution = distro.linux_distribution()  # type: ignore
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
    return _distro.linux_distribution(full_distribution_name)
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
    self.version(),
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_vendor/distro.py", line 741, in version
    self.lsb_release_attr('release'),
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
    return self._lsb_release_info.get(attribute, '')
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_vendor/distro.py", line 556, in __get__
    ret = obj.__dict__[self._fname] = self._f(obj)
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
    stdout = subprocess.check_output(cmd, stderr=devnull)
  File "/home/sutripa/anaconda3/lib/python3.9/subprocess.py", line 424, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/home/sutripa/anaconda3/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/home/sutripa/anaconda3/bin/gget", line 8, in <module>
    sys.exit(main())
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/gget/main.py", line 1551, in main
    alphafold(
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/gget/gget_alphafold.py", line 302, in alphafold
    from alphafold.model import model
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/alphafold/model/model.py", line 20, in <module>
    from alphafold.model import features
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/alphafold/model/features.py", line 19, in <module>
    from alphafold.model.tf import input_pipeline
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/alphafold/model/tf/input_pipeline.py", line 17, in <module>
    from alphafold.model.tf import data_transforms
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/alphafold/model/tf/data_transforms.py", line 18, in <module>
    from alphafold.model.tf import shape_helpers
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/alphafold/model/tf/shape_helpers.py", line 16, in <module>
    import tensorflow.compat.v1 as tf
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/tensorflow/__init__.py", line 51, in <module>
    from ._api.v2 import compat
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/tensorflow/_api/v2/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/__init__.py", line 30, in <module>
    from . import compat
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/__init__.py", line 37, in <module>
    from . import v1
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/compat/v1/__init__.py", line 47, in <module>
    from tensorflow._api.v2.compat.v1 import lite
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/lite/__init__.py", line 9, in <module>
    from . import experimental
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/lite/experimental/__init__.py", line 8, in <module>
    from . import authoring
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/tensorflow/_api/v2/compat/v1/lite/experimental/authoring/__init__.py", line 8, in <module>
    from tensorflow.lite.python.authoring.authoring import compatible
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/authoring/authoring.py", line 43, in <module>
    from tensorflow.lite.python import convert
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/convert.py", line 28, in <module>
    from tensorflow.lite.python import util
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/tensorflow/lite/python/util.py", line 55, in <module>
    from jax import xla_computation as _xla_computation
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/jax/__init__.py", line 35, in <module>
    from jax import config as _config_module
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/jax/config.py", line 17, in <module>
    from jax._src.config import config  # noqa: F401
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/jax/_src/config.py", line 27, in <module>
    from jax._src import lib
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 74, in <module>
    version = check_jaxlib_version(
  File "/home/sutripa/anaconda3/lib/python3.9/site-packages/jax/_src/lib/__init__.py", line 69, in check_jaxlib_version
    raise RuntimeError(msg)
RuntimeError: jaxlib version 0.4.1 is newer than and incompatible with jax version 0.3.25. Please update your jax and/or jaxlib packages.

**Comment by lauraluebbert** [comment]
Hi Sucheta, thank you for reaching out. Please update jax and jaxlib by running `pip install -U jax jaxlib`. Does the error still persist?
