### ISSUE TITLE
gget pdb error in python

### ISSUE THREAD

**Issue by Paulie-ai** [pachterlab/gget#91]
### What happened?

Hi, 
when i uesd command gget pdb 1R42 -o 1R42.pdb, recieved error with 
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/gmx_plumed/bin/gget", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/anaconda3/envs/gmx_plumed/lib/python3.8/site-packages/gget/main.py", line 2102, in main
    pdb_results = pdb(
TypeError: pdb() got an unexpected keyword argument 'verbose'

### gget version

0.27.7

### Operating System (OS)

Linux

### User interface

Command-line

### Are you using a computer with an Apple M1 chip?

Not M1

### What is the exact command that was run?

```shell
gget pdb 1R42 -o 1R42.pdb
```

### Which output/error did you get?

```shell
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/gmx_plumed/bin/gget", line 8, in <module>
    sys.exit(main())
  File "/home/xxx/anaconda3/envs/gmx_plumed/lib/python3.8/site-packages/gget/main.py", line 2102, in main
    pdb_results = pdb(
TypeError: pdb() got an unexpected keyword argument 'verbose'
```

**Comment by Paulie-ai** [comment]
import gget
 gget.pdb("1R42", save=True)
but did not get error.

**Comment by lauraluebbert** [comment]
Hi, thank you very much for bringing this bug to our attention. This is indeed a bug with the gget pdb module which only occurs when gget pdb is called from the command line. We will release a new version tomorrow with a fix

**Comment by lauraluebbert** [comment]
This bug was introduced in version 0.27.5, so in the meantime, you can fix this problem by downgrading gget (`pip install gget==0.27.4`). Sorry about this
